In [8]:
import numpy as np



In [9]:
def createPlane(P1,P2, P3):
    v1 = P2 - P1
    v2 = P3 - P1

    # Calculate the normal vector using the cross product
    v3 = np.cross(v1, v2)



    # Normalize the normal vector (optional)
    v1Norm = v1 / np.linalg.norm(v1)
    v2Norm = v2 / np.linalg.norm(v2)
    v3Norm = v3 / np.linalg.norm(v3)

    return(v1Norm,v2Norm,v3Norm)

def transform(center, v1,v2,v3):

    transform = [[v1[0],v1[1], v1[2], -center[0] ], [v2[0],v2[1], v2[2], -center[1] ],[v3[0],v3[1], v3[2], -center[2] ],[0,0, 0, 1 ]]
    # print(transform)
    return transform

In [16]:
v1 = np.array([2,24,0])
v2 = np.array([8,24,0])
v3 = np.array([2,16,0])

print(createPlane(v1,v2,v3))



(array([1., 0., 0.]), array([ 0., -1.,  0.]), array([ 0.,  0., -1.]))


In [ ]:
center = np.array([1,2,3])
v1 = np.array([1,0,0])
v2 = np.array([0,1,0])
v3 = np.array([0,0,1])


a = transform(center,v1,v2,v3)


pointNotIna = np.array([1,1,1,1])

print()
print(np.matmul(a,pointNotIna))






[ 0 -1 -2  1]


In [11]:
def averagePlaneVectors(vectorArray):
    

    vectorArrayUse = abs(vectorArray)

    print(vectorArrayUse)
    xVectorsBase = [vectorArrayUse[0,:,0]]
    yVectorsBase = [vectorArrayUse[0,:,1]]
    xVectors = [vectorArrayUse[0,:,0]]
    yVectors = [vectorArrayUse[0,:,1]]


    zVectors = vectorArray[:,:,2]


    for x in range(1,len([vectorArray[:,0,0]])):
        cosinex = np.dot(xVectorsBase,vectorArrayUse[x,:,0])/(np.norm(xVectorsBase)*np.norm(vectorArrayUse[x,:,0]))
        cosiney = np.dot(xVectorsBase,vectorArrayUse[x,:,1])/(np.norm(xVectorsBase)*np.norm(vectorArrayUse[x,:,1]))

        if (abs(cosinex) > abs(cosiney)):
            xVectors.append(vectorArrayUse[x,:,0])
            yVectors.append(vectorArrayUse[x,:,1])
        else:
            xVectors.append(vectorArrayUse[x,:,1])
            yVectors.append(vectorArrayUse[x,:,0])


    return(xVectors,yVectors,zVectors)


In [12]:
center = np.array([1,2,3])
v1 = np.array([1,0,0])
v2 = np.array([0,1,0])
v3 = np.array([0,0,1])


a = transform(center,v1,v2,v3)

center = np.array([1,2,3])
v1 = np.array([1,0,0])
v2 = np.array([0,1,0])
v3 = np.array([0,12,-1])


b = transform(center,v1,v2,v3)

center = np.array([1,2,3])
v1 = np.array([1,0,0])
v2 = np.array([0,1,0])
v3 = np.array([-3,0,2])


c= transform(center,v1,v2,v3)

allArray = np.array([a,b,c])


print(allArray)
print()
print(allArray[:,:,2])

print()

print(len(allArray[:,0,0]))

print(averagePlaneVectors(allArray))


[[[ 1  0  0 -1]
  [ 0  1  0 -2]
  [ 0  0  1 -3]
  [ 0  0  0  1]]

 [[ 1  0  0 -1]
  [ 0  1  0 -2]
  [ 0 12 -1 -3]
  [ 0  0  0  1]]

 [[ 1  0  0 -1]
  [ 0  1  0 -2]
  [-3  0  2 -3]
  [ 0  0  0  1]]]

[[ 0  0  1  0]
 [ 0  0 -1  0]
 [ 0  0  2  0]]

3
[[[ 1  0  0  1]
  [ 0  1  0  2]
  [ 0  0  1  3]
  [ 0  0  0  1]]

 [[ 1  0  0  1]
  [ 0  1  0  2]
  [ 0 12  1  3]
  [ 0  0  0  1]]

 [[ 1  0  0  1]
  [ 0  1  0  2]
  [ 3  0  2  3]
  [ 0  0  0  1]]]
([array([1, 0, 0, 0])], [array([0, 1, 0, 0])], array([[ 0,  0,  1,  0],
       [ 0,  0, -1,  0],
       [ 0,  0,  2,  0]]))
